site_name: backend
site_description: Chat application built with django and vuejs
repo_url: https://github.com/Tobi-De/djchat
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Tobi-De">Tobi-De</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
